<section class="mt-3 card card-body">
    <h1>Novo Aluno</h1>
    <div class="row">
        <div class="cool">
            <form method="POST">
                <label for="nome">Nome</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">

                <label for="cpf">Cpf</label>
                <input name="cpf" type="text" id="cpf" class="form-control mb-3">

                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-3">

                <label for="nascimento">Data De Nascimento</label>
                <input name="nascimento" type="date" id="nascimento" class="form-control mb-3">

                <label for="genero">Genero</label>
                <input name="genero" type="text" id="genero" class="form-control mb-3">


                <button class="btn btn-primary">Pronto</button>

            </form>
        </div>
    </div>
</section>